// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TournamentStatus int32

const (
	TournamentStatus_TOURNAMENT_STATUS_UNSPECIFIED TournamentStatus = 0
	TournamentStatus_TOURNAMENT_STATUS_DRAFT       TournamentStatus = 1
	TournamentStatus_TOURNAMENT_STATUS_ACTIVE      TournamentStatus = 2
	TournamentStatus_TOURNAMENT_STATUS_STARTED     TournamentStatus = 3
	TournamentStatus_TOURNAMENT_STATUS_COMPLETED   TournamentStatus = 4
	TournamentStatus_TOURNAMENT_STATUS_CANCELLED   TournamentStatus = 5
)

// Enum value maps for TournamentStatus.
var (
	TournamentStatus_name = map[int32]string{
		0: "TOURNAMENT_STATUS_UNSPECIFIED",
		1: "TOURNAMENT_STATUS_DRAFT",
		2: "TOURNAMENT_STATUS_ACTIVE",
		3: "TOURNAMENT_STATUS_STARTED",
		4: "TOURNAMENT_STATUS_COMPLETED",
		5: "TOURNAMENT_STATUS_CANCELLED",
	}
	TournamentStatus_value = map[string]int32{
		"TOURNAMENT_STATUS_UNSPECIFIED": 0,
		"TOURNAMENT_STATUS_DRAFT":       1,
		"TOURNAMENT_STATUS_ACTIVE":      2,
		"TOURNAMENT_STATUS_STARTED":     3,
		"TOURNAMENT_STATUS_COMPLETED":   4,
		"TOURNAMENT_STATUS_CANCELLED":   5,
	}
)

func (x TournamentStatus) Enum() *TournamentStatus {
	p := new(TournamentStatus)
	*p = x
	return p
}

func (x TournamentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TournamentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (TournamentStatus) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x TournamentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TournamentStatus.Descriptor instead.
func (TournamentStatus) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type MatchStatus int32

const (
	MatchStatus_MATCH_STATUS_UNSPECIFIED MatchStatus = 0
	MatchStatus_MATCH_STATUS_SCHEDULED   MatchStatus = 1
	MatchStatus_MATCH_STATUS_IN_PROGRESS MatchStatus = 2
	MatchStatus_MATCH_STATUS_COMPLETED   MatchStatus = 3
	MatchStatus_MATCH_STATUS_CANCELLED   MatchStatus = 4
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "MATCH_STATUS_UNSPECIFIED",
		1: "MATCH_STATUS_SCHEDULED",
		2: "MATCH_STATUS_IN_PROGRESS",
		3: "MATCH_STATUS_COMPLETED",
		4: "MATCH_STATUS_CANCELLED",
	}
	MatchStatus_value = map[string]int32{
		"MATCH_STATUS_UNSPECIFIED": 0,
		"MATCH_STATUS_SCHEDULED":   1,
		"MATCH_STATUS_IN_PROGRESS": 2,
		"MATCH_STATUS_COMPLETED":   3,
		"MATCH_STATUS_CANCELLED":   4,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

type TournamentParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TournamentParticipant) Reset() {
	*x = TournamentParticipant{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TournamentParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TournamentParticipant) ProtoMessage() {}

func (x *TournamentParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TournamentParticipant.ProtoReflect.Descriptor instead.
func (*TournamentParticipant) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *TournamentParticipant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TournamentParticipant) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TournamentParticipant) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	TournamentId  string                 `protobuf:"bytes,5,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Participant) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *Participant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Participant) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Participant) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Participant) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *Participant) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Participant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Tournament struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TournamentId        string                 `protobuf:"bytes,1,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxParticipants     int32                  `protobuf:"varint,4,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	CurrentParticipants int32                  `protobuf:"varint,5,opt,name=current_participants,json=currentParticipants,proto3" json:"current_participants,omitempty"`
	Status              TournamentStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=tournament.TournamentStatus" json:"status,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartTime           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Tournament) Reset() {
	*x = Tournament{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tournament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tournament) ProtoMessage() {}

func (x *Tournament) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tournament.ProtoReflect.Descriptor instead.
func (*Tournament) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *Tournament) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *Tournament) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tournament) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tournament) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *Tournament) GetCurrentParticipants() int32 {
	if x != nil {
		return x.CurrentParticipants
	}
	return 0
}

func (x *Tournament) GetStatus() TournamentStatus {
	if x != nil {
		return x.Status
	}
	return TournamentStatus_TOURNAMENT_STATUS_UNSPECIFIED
}

func (x *Tournament) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tournament) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Tournament) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Tournament) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateTournamentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,4,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTournamentRequest) Reset() {
	*x = CreateTournamentRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTournamentRequest) ProtoMessage() {}

func (x *CreateTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTournamentRequest.ProtoReflect.Descriptor instead.
func (*CreateTournamentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateTournamentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTournamentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTournamentRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *CreateTournamentRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateTournamentRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *Tournament            `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTournamentResponse) Reset() {
	*x = CreateTournamentResponse{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTournamentResponse) ProtoMessage() {}

func (x *CreateTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTournamentResponse.ProtoReflect.Descriptor instead.
func (*CreateTournamentResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTournamentResponse) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type ListTournamentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        TournamentStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=tournament.TournamentStatus" json:"status,omitempty"`
	StartDateFrom *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date_from,json=startDateFrom,proto3" json:"start_date_from,omitempty"`
	StartDateTo   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_date_to,json=startDateTo,proto3" json:"start_date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTournamentsRequest) Reset() {
	*x = ListTournamentsRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTournamentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTournamentsRequest) ProtoMessage() {}

func (x *ListTournamentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTournamentsRequest.ProtoReflect.Descriptor instead.
func (*ListTournamentsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListTournamentsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListTournamentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTournamentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTournamentsRequest) GetStatus() TournamentStatus {
	if x != nil {
		return x.Status
	}
	return TournamentStatus_TOURNAMENT_STATUS_UNSPECIFIED
}

func (x *ListTournamentsRequest) GetStartDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDateFrom
	}
	return nil
}

func (x *ListTournamentsRequest) GetStartDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDateTo
	}
	return nil
}

type ListTournamentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournaments   []*Tournament          `protobuf:"bytes,1,rep,name=tournaments,proto3" json:"tournaments,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTournamentsResponse) Reset() {
	*x = ListTournamentsResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTournamentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTournamentsResponse) ProtoMessage() {}

func (x *ListTournamentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTournamentsResponse.ProtoReflect.Descriptor instead.
func (*ListTournamentsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListTournamentsResponse) GetTournaments() []*Tournament {
	if x != nil {
		return x.Tournaments
	}
	return nil
}

func (x *ListTournamentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentRequest) Reset() {
	*x = GetTournamentRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentRequest) ProtoMessage() {}

func (x *GetTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentRequest.ProtoReflect.Descriptor instead.
func (*GetTournamentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type GetTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *Tournament            `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentResponse) Reset() {
	*x = GetTournamentResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentResponse) ProtoMessage() {}

func (x *GetTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentResponse.ProtoReflect.Descriptor instead.
func (*GetTournamentResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTournamentResponse) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type ActivateTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateTournamentRequest) Reset() {
	*x = ActivateTournamentRequest{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateTournamentRequest) ProtoMessage() {}

func (x *ActivateTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateTournamentRequest.ProtoReflect.Descriptor instead.
func (*ActivateTournamentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *ActivateTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ActivateTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type ActivateTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *Tournament            `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateTournamentResponse) Reset() {
	*x = ActivateTournamentResponse{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateTournamentResponse) ProtoMessage() {}

func (x *ActivateTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateTournamentResponse.ProtoReflect.Descriptor instead.
func (*ActivateTournamentResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *ActivateTournamentResponse) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type StartTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTournamentRequest) Reset() {
	*x = StartTournamentRequest{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTournamentRequest) ProtoMessage() {}

func (x *StartTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTournamentRequest.ProtoReflect.Descriptor instead.
func (*StartTournamentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *StartTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StartTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type StartTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *Tournament            `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTournamentResponse) Reset() {
	*x = StartTournamentResponse{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTournamentResponse) ProtoMessage() {}

func (x *StartTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTournamentResponse.ProtoReflect.Descriptor instead.
func (*StartTournamentResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *StartTournamentResponse) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type CancelTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTournamentRequest) Reset() {
	*x = CancelTournamentRequest{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTournamentRequest) ProtoMessage() {}

func (x *CancelTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTournamentRequest.ProtoReflect.Descriptor instead.
func (*CancelTournamentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *CancelTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CancelTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type CancelTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *Tournament            `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTournamentResponse) Reset() {
	*x = CancelTournamentResponse{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTournamentResponse) ProtoMessage() {}

func (x *CancelTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTournamentResponse.ProtoReflect.Descriptor instead.
func (*CancelTournamentResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *CancelTournamentResponse) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type RegisterForTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterForTournamentRequest) Reset() {
	*x = RegisterForTournamentRequest{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterForTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterForTournamentRequest) ProtoMessage() {}

func (x *RegisterForTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterForTournamentRequest.ProtoReflect.Descriptor instead.
func (*RegisterForTournamentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterForTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterForTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type RegisterForTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParticipantId string                 `protobuf:"bytes,1,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterForTournamentResponse) Reset() {
	*x = RegisterForTournamentResponse{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterForTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterForTournamentResponse) ProtoMessage() {}

func (x *RegisterForTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterForTournamentResponse.ProtoReflect.Descriptor instead.
func (*RegisterForTournamentResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterForTournamentResponse) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *RegisterForTournamentResponse) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *RegisterForTournamentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterForTournamentResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type GetTournamentParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentParticipantsRequest) Reset() {
	*x = GetTournamentParticipantsRequest{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentParticipantsRequest) ProtoMessage() {}

func (x *GetTournamentParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentParticipantsRequest.ProtoReflect.Descriptor instead.
func (*GetTournamentParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetTournamentParticipantsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetTournamentParticipantsRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *GetTournamentParticipantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTournamentParticipantsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetTournamentParticipantsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Participants      []*Participant         `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	TotalParticipants int32                  `protobuf:"varint,2,opt,name=total_participants,json=totalParticipants,proto3" json:"total_participants,omitempty"`
	NextPageToken     string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTournamentParticipantsResponse) Reset() {
	*x = GetTournamentParticipantsResponse{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentParticipantsResponse) ProtoMessage() {}

func (x *GetTournamentParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentParticipantsResponse.ProtoReflect.Descriptor instead.
func (*GetTournamentParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetTournamentParticipantsResponse) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *GetTournamentParticipantsResponse) GetTotalParticipants() int32 {
	if x != nil {
		return x.TotalParticipants
	}
	return 0
}

func (x *GetTournamentParticipantsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RemoveParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantRequest) Reset() {
	*x = RemoveParticipantRequest{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantRequest) ProtoMessage() {}

func (x *RemoveParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantRequest.ProtoReflect.Descriptor instead.
func (*RemoveParticipantRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveParticipantRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RemoveParticipantRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *RemoveParticipantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TournamentId  string                 `protobuf:"bytes,1,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Removed       bool                   `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantResponse) Reset() {
	*x = RemoveParticipantResponse{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantResponse) ProtoMessage() {}

func (x *RemoveParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantResponse.ProtoReflect.Descriptor instead.
func (*RemoveParticipantResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveParticipantResponse) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *RemoveParticipantResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveParticipantResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type Match struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MatchId         string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	TournamentId    string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	Round           int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Position        int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	Participant1    *TournamentParticipant `protobuf:"bytes,5,opt,name=participant1,proto3" json:"participant1,omitempty"`
	Participant2    *TournamentParticipant `protobuf:"bytes,6,opt,name=participant2,proto3" json:"participant2,omitempty"`
	Winner          string                 `protobuf:"bytes,7,opt,name=winner,proto3" json:"winner,omitempty"`
	Status          MatchStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=tournament.MatchStatus" json:"status,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	NextMatchId     string                 `protobuf:"bytes,11,opt,name=next_match_id,json=nextMatchId,proto3" json:"next_match_id,omitempty"`
	SourceMatch_1Id string                 `protobuf:"bytes,12,opt,name=source_match_1_id,json=sourceMatch1Id,proto3" json:"source_match_1_id,omitempty"`
	SourceMatch_2Id string                 `protobuf:"bytes,13,opt,name=source_match_2_id,json=sourceMatch2Id,proto3" json:"source_match_2_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *Match) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *Match) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *Match) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *Match) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Match) GetParticipant1() *TournamentParticipant {
	if x != nil {
		return x.Participant1
	}
	return nil
}

func (x *Match) GetParticipant2() *TournamentParticipant {
	if x != nil {
		return x.Participant2
	}
	return nil
}

func (x *Match) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *Match) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_MATCH_STATUS_UNSPECIFIED
}

func (x *Match) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Match) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Match) GetNextMatchId() string {
	if x != nil {
		return x.NextMatchId
	}
	return ""
}

func (x *Match) GetSourceMatch_1Id() string {
	if x != nil {
		return x.SourceMatch_1Id
	}
	return ""
}

func (x *Match) GetSourceMatch_2Id() string {
	if x != nil {
		return x.SourceMatch_2Id
	}
	return ""
}

type GetTournamentMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	Round         int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentMatchesRequest) Reset() {
	*x = GetTournamentMatchesRequest{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentMatchesRequest) ProtoMessage() {}

func (x *GetTournamentMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentMatchesRequest.ProtoReflect.Descriptor instead.
func (*GetTournamentMatchesRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetTournamentMatchesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetTournamentMatchesRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *GetTournamentMatchesRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type GetTournamentMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	TotalRounds   int32                  `protobuf:"varint,2,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	CurrentRound  int32                  `protobuf:"varint,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentMatchesResponse) Reset() {
	*x = GetTournamentMatchesResponse{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentMatchesResponse) ProtoMessage() {}

func (x *GetTournamentMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentMatchesResponse.ProtoReflect.Descriptor instead.
func (*GetTournamentMatchesResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetTournamentMatchesResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *GetTournamentMatchesResponse) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *GetTournamentMatchesResponse) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

type GetMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	MatchId       string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchRequest) Reset() {
	*x = GetMatchRequest{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchRequest) ProtoMessage() {}

func (x *GetMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchRequest.ProtoReflect.Descriptor instead.
func (*GetMatchRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetMatchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetMatchRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *GetMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type GetMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchResponse) Reset() {
	*x = GetMatchResponse{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchResponse) ProtoMessage() {}

func (x *GetMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchResponse.ProtoReflect.Descriptor instead.
func (*GetMatchResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetMatchResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type SubmitMatchResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	MatchId       string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	WinnerUserId  string                 `protobuf:"bytes,4,opt,name=winner_user_id,json=winnerUserId,proto3" json:"winner_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMatchResultRequest) Reset() {
	*x = SubmitMatchResultRequest{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMatchResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMatchResultRequest) ProtoMessage() {}

func (x *SubmitMatchResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMatchResultRequest.ProtoReflect.Descriptor instead.
func (*SubmitMatchResultRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *SubmitMatchResultRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SubmitMatchResultRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *SubmitMatchResultRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *SubmitMatchResultRequest) GetWinnerUserId() string {
	if x != nil {
		return x.WinnerUserId
	}
	return ""
}

type SubmitMatchResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMatchResultResponse) Reset() {
	*x = SubmitMatchResultResponse{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMatchResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMatchResultResponse) ProtoMessage() {}

func (x *SubmitMatchResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMatchResultResponse.ProtoReflect.Descriptor instead.
func (*SubmitMatchResultResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

func (x *SubmitMatchResultResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type AdminSubmitMatchResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	MatchId       string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	WinnerUserId  string                 `protobuf:"bytes,4,opt,name=winner_user_id,json=winnerUserId,proto3" json:"winner_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSubmitMatchResultRequest) Reset() {
	*x = AdminSubmitMatchResultRequest{}
	mi := &file_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSubmitMatchResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSubmitMatchResultRequest) ProtoMessage() {}

func (x *AdminSubmitMatchResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSubmitMatchResultRequest.ProtoReflect.Descriptor instead.
func (*AdminSubmitMatchResultRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{28}
}

func (x *AdminSubmitMatchResultRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AdminSubmitMatchResultRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *AdminSubmitMatchResultRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *AdminSubmitMatchResultRequest) GetWinnerUserId() string {
	if x != nil {
		return x.WinnerUserId
	}
	return ""
}

type AdminSubmitMatchResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSubmitMatchResultResponse) Reset() {
	*x = AdminSubmitMatchResultResponse{}
	mi := &file_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSubmitMatchResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSubmitMatchResultResponse) ProtoMessage() {}

func (x *AdminSubmitMatchResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSubmitMatchResultResponse.ProtoReflect.Descriptor instead.
func (*AdminSubmitMatchResultResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{29}
}

func (x *AdminSubmitMatchResultResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\n" +
	"tournament\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x10permission.proto\"o\n" +
	"\x15TournamentParticipant\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"\xad\x02\n" +
	"\vParticipant\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12#\n" +
	"\rtournament_id\x18\x05 \x01(\tR\ftournamentId\x12?\n" +
	"\rregistered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe3\x03\n" +
	"\n" +
	"Tournament\x12#\n" +
	"\rtournament_id\x18\x01 \x01(\tR\ftournamentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10max_participants\x18\x04 \x01(\x05R\x0fmaxParticipants\x121\n" +
	"\x14current_participants\x18\x05 \x01(\x05R\x13currentParticipants\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.tournament.TournamentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x8a\x02\n" +
	"\x17CreateTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10max_participants\x18\x04 \x01(\x05R\x0fmaxParticipants\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"R\n" +
	"\x18CreateTournamentResponse\x126\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x16.tournament.TournamentR\n" +
	"tournament\"\x9e\x02\n" +
	"\x16ListTournamentsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.tournament.TournamentStatusR\x06status\x12B\n" +
	"\x0fstart_date_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rstartDateFrom\x12>\n" +
	"\rstart_date_to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vstartDateTo\"t\n" +
	"\x17ListTournamentsResponse\x128\n" +
	"\vtournaments\x18\x01 \x03(\v2\x16.tournament.TournamentR\vtournaments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"Y\n" +
	"\x14GetTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"O\n" +
	"\x15GetTournamentResponse\x126\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x16.tournament.TournamentR\n" +
	"tournament\"^\n" +
	"\x19ActivateTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"T\n" +
	"\x1aActivateTournamentResponse\x126\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x16.tournament.TournamentR\n" +
	"tournament\"[\n" +
	"\x16StartTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"Q\n" +
	"\x17StartTournamentResponse\x126\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x16.tournament.TournamentR\n" +
	"tournament\"\\\n" +
	"\x17CancelTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"R\n" +
	"\x18CancelTournamentResponse\x126\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x16.tournament.TournamentR\n" +
	"tournament\"a\n" +
	"\x1cRegisterForTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"\xc5\x01\n" +
	"\x1dRegisterForTournamentResponse\x12%\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tR\rparticipantId\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12?\n" +
	"\rregistered_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"\xa1\x01\n" +
	" GetTournamentParticipantsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xb7\x01\n" +
	"!GetTournamentParticipantsResponse\x12;\n" +
	"\fparticipants\x18\x01 \x03(\v2\x17.tournament.ParticipantR\fparticipants\x12-\n" +
	"\x12total_participants\x18\x02 \x01(\x05R\x11totalParticipants\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"v\n" +
	"\x18RemoveParticipantRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"s\n" +
	"\x19RemoveParticipantResponse\x12#\n" +
	"\rtournament_id\x18\x01 \x01(\tR\ftournamentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\aremoved\x18\x03 \x01(\bR\aremoved\"\xc4\x04\n" +
	"\x05Match\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12E\n" +
	"\fparticipant1\x18\x05 \x01(\v2!.tournament.TournamentParticipantR\fparticipant1\x12E\n" +
	"\fparticipant2\x18\x06 \x01(\v2!.tournament.TournamentParticipantR\fparticipant2\x12\x16\n" +
	"\x06winner\x18\a \x01(\tR\x06winner\x12/\n" +
	"\x06status\x18\b \x01(\x0e2\x17.tournament.MatchStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\"\n" +
	"\rnext_match_id\x18\v \x01(\tR\vnextMatchId\x12)\n" +
	"\x11source_match_1_id\x18\f \x01(\tR\x0esourceMatch1Id\x12)\n" +
	"\x11source_match_2_id\x18\r \x01(\tR\x0esourceMatch2Id\"v\n" +
	"\x1bGetTournamentMatchesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\"\x93\x01\n" +
	"\x1cGetTournamentMatchesResponse\x12+\n" +
	"\amatches\x18\x01 \x03(\v2\x11.tournament.MatchR\amatches\x12!\n" +
	"\ftotal_rounds\x18\x02 \x01(\x05R\vtotalRounds\x12#\n" +
	"\rcurrent_round\x18\x03 \x01(\x05R\fcurrentRound\"o\n" +
	"\x0fGetMatchRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\";\n" +
	"\x10GetMatchResponse\x12'\n" +
	"\x05match\x18\x01 \x01(\v2\x11.tournament.MatchR\x05match\"\x9e\x01\n" +
	"\x18SubmitMatchResultRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\x12$\n" +
	"\x0ewinner_user_id\x18\x04 \x01(\tR\fwinnerUserId\"D\n" +
	"\x19SubmitMatchResultResponse\x12'\n" +
	"\x05match\x18\x01 \x01(\v2\x11.tournament.MatchR\x05match\"\xa3\x01\n" +
	"\x1dAdminSubmitMatchResultRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\x12$\n" +
	"\x0ewinner_user_id\x18\x04 \x01(\tR\fwinnerUserId\"I\n" +
	"\x1eAdminSubmitMatchResultResponse\x12'\n" +
	"\x05match\x18\x01 \x01(\v2\x11.tournament.MatchR\x05match*\xd1\x01\n" +
	"\x10TournamentStatus\x12!\n" +
	"\x1dTOURNAMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TOURNAMENT_STATUS_DRAFT\x10\x01\x12\x1c\n" +
	"\x18TOURNAMENT_STATUS_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19TOURNAMENT_STATUS_STARTED\x10\x03\x12\x1f\n" +
	"\x1bTOURNAMENT_STATUS_COMPLETED\x10\x04\x12\x1f\n" +
	"\x1bTOURNAMENT_STATUS_CANCELLED\x10\x05*\x9d\x01\n" +
	"\vMatchStatus\x12\x1c\n" +
	"\x18MATCH_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MATCH_STATUS_SCHEDULED\x10\x01\x12\x1c\n" +
	"\x18MATCH_STATUS_IN_PROGRESS\x10\x02\x12\x1a\n" +
	"\x16MATCH_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16MATCH_STATUS_CANCELLED\x10\x042\xdb\x1f\n" +
	"\x11TournamentService\x12\xb0\x02\n" +
	"\x10CreateTournament\x12#.tournament.CreateTournamentRequest\x1a$.tournament.CreateTournamentResponse\"\xd0\x01\x92Ai\x12\x11Create Tournament\x1a4Create a new tournament with specified configurationb\x1e\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\n" +
	"\x10\n" +
	"\fServiceToken\x12\x00\x8a\xb5\x18&ADMIN:NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x01\x82\xd3\xe4\x93\x020:\x01*\"+/v1/admin/namespace/{namespace}/tournaments\x12\xb1\x02\n" +
	"\x0fListTournaments\x12\".tournament.ListTournamentsRequest\x1a#.tournament.ListTournamentsResponse\"\xd4\x01\x92Au\x12\x10List Tournaments\x1aAList tournaments with optional filtering by status and date rangeb\x1e\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\n" +
	"\x10\n" +
	"\fServiceToken\x12\x00\x8a\xb5\x18 NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02.\x12,/v1/public/namespace/{namespace}/tournaments\x12\x9f\x02\n" +
	"\rGetTournament\x12 .tournament.GetTournamentRequest\x1a!.tournament.GetTournamentResponse\"\xc8\x01\x92AY\x12\x0eGet Tournament\x1a'Get tournament details by tournament IDb\x1e\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\n" +
	"\x10\n" +
	"\fServiceToken\x12\x00\x8a\xb5\x18 NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02>\x12</v1/public/namespace/{namespace}/tournaments/{tournament_id}\x12\xd8\x02\n" +
	"\x12ActivateTournament\x12%.tournament.ActivateTournamentRequest\x1a&.tournament.ActivateTournamentResponse\"\xf2\x01\x92Ar\x12\x13Activate Tournament\x1a;Activate a tournament to open registration for participantsb\x1e\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\n" +
	"\x10\n" +
	"\fServiceToken\x12\x00\x8a\xb5\x18&ADMIN:NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02I:\x01*\"D/v1/admin/namespace/{namespace}/tournaments/{tournament_id}/activate\x12\xcb\x02\n" +
	"\x0fStartTournament\x12\".tournament.StartTournamentRequest\x1a#.tournament.StartTournamentResponse\"\xee\x01\x92Aq\x12\x10Start Tournament\x1a=Start a tournament to generate brackets and begin competitionb\x1e\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\n" +
	"\x10\n" +
	"\fServiceToken\x12\x00\x8a\xb5\x18&ADMIN:NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02F:\x01*\"A/v1/admin/namespace/{namespace}/tournaments/{tournament_id}/start\x12\xc8\x02\n" +
	"\x10CancelTournament\x12#.tournament.CancelTournamentRequest\x1a$.tournament.CancelTournamentResponse\"\xe8\x01\x92Aj\x12\x11Cancel Tournament\x1a5Cancel a tournament and prevent further participationb\x1e\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\n" +
	"\x10\n" +
	"\fServiceToken\x12\x00\x8a\xb5\x18&ADMIN:NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02G:\x01*\"B/v1/admin/namespace/{namespace}/tournaments/{tournament_id}/cancel\x12\xa1\x02\n" +
	"\x15RegisterForTournament\x12(.tournament.RegisterForTournamentRequest\x1a).tournament.RegisterForTournamentResponse\"\xb2\x01\x92A_\x12\x17Register for Tournament\x1a6Register user for tournament with capacity enforcementb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02J:\x01*\"E/v1/public/namespace/{namespace}/tournaments/{tournament_id}/register\x12\xb2\x02\n" +
	"\x19GetTournamentParticipants\x12,.tournament.GetTournamentParticipantsRequest\x1a-.tournament.GetTournamentParticipantsResponse\"\xb7\x01\x92Ac\x12\x1bGet Tournament Participants\x1a6List all participants for a tournament with paginationb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02K\x12I/v1/public/namespace/{namespace}/tournaments/{tournament_id}/participants\x12\x9d\x02\n" +
	"\x11RemoveParticipant\x12$.tournament.RemoveParticipantRequest\x1a%.tournament.RemoveParticipantResponse\"\xba\x01\x92A]\x12\x1dRemove Tournament Participant\x1a.Admin-only: Remove participant from tournamentb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02T*R/v1/admin/namespace/{namespace}/tournaments/{tournament_id}/participants/{user_id}\x12\xa8\x02\n" +
	"\x14GetTournamentMatches\x12'.tournament.GetTournamentMatchesRequest\x1a(.tournament.GetTournamentMatchesResponse\"\xbc\x01\x92Am\x12\x16Get Tournament Matches\x1a3Get all matches for a tournament organized by roundb\x1e\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\n" +
	"\x10\n" +
	"\fServiceToken\x12\x00\x82\xd3\xe4\x93\x02F\x12D/v1/public/namespace/{namespace}/tournaments/{tournament_id}/matches\x12\x86\x02\n" +
	"\bGetMatch\x12\x1b.tournament.GetMatchRequest\x1a\x1c.tournament.GetMatchResponse\"\xbe\x01\x92Ad\x12\x11Get Match Details\x1a/Get detailed information about a specific matchb\x1e\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\n" +
	"\x10\n" +
	"\fServiceToken\x12\x00\x82\xd3\xe4\x93\x02Q\x12O/v1/public/namespace/{namespace}/tournaments/{tournament_id}/matches/{match_id}\x12\xa9\x02\n" +
	"\x11SubmitMatchResult\x12$.tournament.SubmitMatchResultRequest\x1a%.tournament.SubmitMatchResultResponse\"\xc6\x01\x92Ac\x12\x13Submit Match Result\x1a8Game server: Submit match result with winner informationb\x12\n" +
	"\x10\n" +
	"\fServiceToken\x12\x00\x82\xd3\xe4\x93\x02Z:\x01*\"U/v1/admin/namespace/{namespace}/tournaments/{tournament_id}/matches/{match_id}/result\x12\xef\x02\n" +
	"\x16AdminSubmitMatchResult\x12).tournament.AdminSubmitMatchResultRequest\x1a*.tournament.AdminSubmitMatchResultResponse\"\xfd\x01\x92Af\x12\x19Admin Submit Match Result\x1a;Admin override: Submit match result with winner informationb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18&ADMIN:NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02`:\x01*\"[/v1/admin/namespace/{namespace}/tournaments/{tournament_id}/matches/{match_id}/result/adminB\xc9\x02\x92A\xd6\x01\x12\x15\n" +
	"\x0eTournament API2\x031.0\"\v/tournamentZ\xaf\x01\n" +
	"X\n" +
	"\x06Bearer\x12N\b\x02\x129User Bearer token for authentication (from AccelByte IAM)\x1a\rAuthorization \x02\n" +
	"S\n" +
	"\fServiceToken\x12C\b\x02\x12,Service token for game server authentication\x1a\x0fX-Service-Token \x02\n" +
	"%net.accelbyte.extend.serviceextensionP\x01Z extend-tournament-service/pkg/pb\xaa\x02!AccelByte.Extend.ServiceExtensionb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_service_proto_goTypes = []any{
	(TournamentStatus)(0),                     // 0: tournament.TournamentStatus
	(MatchStatus)(0),                          // 1: tournament.MatchStatus
	(*TournamentParticipant)(nil),             // 2: tournament.TournamentParticipant
	(*Participant)(nil),                       // 3: tournament.Participant
	(*Tournament)(nil),                        // 4: tournament.Tournament
	(*CreateTournamentRequest)(nil),           // 5: tournament.CreateTournamentRequest
	(*CreateTournamentResponse)(nil),          // 6: tournament.CreateTournamentResponse
	(*ListTournamentsRequest)(nil),            // 7: tournament.ListTournamentsRequest
	(*ListTournamentsResponse)(nil),           // 8: tournament.ListTournamentsResponse
	(*GetTournamentRequest)(nil),              // 9: tournament.GetTournamentRequest
	(*GetTournamentResponse)(nil),             // 10: tournament.GetTournamentResponse
	(*ActivateTournamentRequest)(nil),         // 11: tournament.ActivateTournamentRequest
	(*ActivateTournamentResponse)(nil),        // 12: tournament.ActivateTournamentResponse
	(*StartTournamentRequest)(nil),            // 13: tournament.StartTournamentRequest
	(*StartTournamentResponse)(nil),           // 14: tournament.StartTournamentResponse
	(*CancelTournamentRequest)(nil),           // 15: tournament.CancelTournamentRequest
	(*CancelTournamentResponse)(nil),          // 16: tournament.CancelTournamentResponse
	(*RegisterForTournamentRequest)(nil),      // 17: tournament.RegisterForTournamentRequest
	(*RegisterForTournamentResponse)(nil),     // 18: tournament.RegisterForTournamentResponse
	(*GetTournamentParticipantsRequest)(nil),  // 19: tournament.GetTournamentParticipantsRequest
	(*GetTournamentParticipantsResponse)(nil), // 20: tournament.GetTournamentParticipantsResponse
	(*RemoveParticipantRequest)(nil),          // 21: tournament.RemoveParticipantRequest
	(*RemoveParticipantResponse)(nil),         // 22: tournament.RemoveParticipantResponse
	(*Match)(nil),                             // 23: tournament.Match
	(*GetTournamentMatchesRequest)(nil),       // 24: tournament.GetTournamentMatchesRequest
	(*GetTournamentMatchesResponse)(nil),      // 25: tournament.GetTournamentMatchesResponse
	(*GetMatchRequest)(nil),                   // 26: tournament.GetMatchRequest
	(*GetMatchResponse)(nil),                  // 27: tournament.GetMatchResponse
	(*SubmitMatchResultRequest)(nil),          // 28: tournament.SubmitMatchResultRequest
	(*SubmitMatchResultResponse)(nil),         // 29: tournament.SubmitMatchResultResponse
	(*AdminSubmitMatchResultRequest)(nil),     // 30: tournament.AdminSubmitMatchResultRequest
	(*AdminSubmitMatchResultResponse)(nil),    // 31: tournament.AdminSubmitMatchResultResponse
	(*timestamppb.Timestamp)(nil),             // 32: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	32, // 0: tournament.Participant.registered_at:type_name -> google.protobuf.Timestamp
	32, // 1: tournament.Participant.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: tournament.Tournament.status:type_name -> tournament.TournamentStatus
	32, // 3: tournament.Tournament.created_at:type_name -> google.protobuf.Timestamp
	32, // 4: tournament.Tournament.updated_at:type_name -> google.protobuf.Timestamp
	32, // 5: tournament.Tournament.start_time:type_name -> google.protobuf.Timestamp
	32, // 6: tournament.Tournament.end_time:type_name -> google.protobuf.Timestamp
	32, // 7: tournament.CreateTournamentRequest.start_time:type_name -> google.protobuf.Timestamp
	32, // 8: tournament.CreateTournamentRequest.end_time:type_name -> google.protobuf.Timestamp
	4,  // 9: tournament.CreateTournamentResponse.tournament:type_name -> tournament.Tournament
	0,  // 10: tournament.ListTournamentsRequest.status:type_name -> tournament.TournamentStatus
	32, // 11: tournament.ListTournamentsRequest.start_date_from:type_name -> google.protobuf.Timestamp
	32, // 12: tournament.ListTournamentsRequest.start_date_to:type_name -> google.protobuf.Timestamp
	4,  // 13: tournament.ListTournamentsResponse.tournaments:type_name -> tournament.Tournament
	4,  // 14: tournament.GetTournamentResponse.tournament:type_name -> tournament.Tournament
	4,  // 15: tournament.ActivateTournamentResponse.tournament:type_name -> tournament.Tournament
	4,  // 16: tournament.StartTournamentResponse.tournament:type_name -> tournament.Tournament
	4,  // 17: tournament.CancelTournamentResponse.tournament:type_name -> tournament.Tournament
	32, // 18: tournament.RegisterForTournamentResponse.registered_at:type_name -> google.protobuf.Timestamp
	3,  // 19: tournament.GetTournamentParticipantsResponse.participants:type_name -> tournament.Participant
	2,  // 20: tournament.Match.participant1:type_name -> tournament.TournamentParticipant
	2,  // 21: tournament.Match.participant2:type_name -> tournament.TournamentParticipant
	1,  // 22: tournament.Match.status:type_name -> tournament.MatchStatus
	32, // 23: tournament.Match.started_at:type_name -> google.protobuf.Timestamp
	32, // 24: tournament.Match.completed_at:type_name -> google.protobuf.Timestamp
	23, // 25: tournament.GetTournamentMatchesResponse.matches:type_name -> tournament.Match
	23, // 26: tournament.GetMatchResponse.match:type_name -> tournament.Match
	23, // 27: tournament.SubmitMatchResultResponse.match:type_name -> tournament.Match
	23, // 28: tournament.AdminSubmitMatchResultResponse.match:type_name -> tournament.Match
	5,  // 29: tournament.TournamentService.CreateTournament:input_type -> tournament.CreateTournamentRequest
	7,  // 30: tournament.TournamentService.ListTournaments:input_type -> tournament.ListTournamentsRequest
	9,  // 31: tournament.TournamentService.GetTournament:input_type -> tournament.GetTournamentRequest
	11, // 32: tournament.TournamentService.ActivateTournament:input_type -> tournament.ActivateTournamentRequest
	13, // 33: tournament.TournamentService.StartTournament:input_type -> tournament.StartTournamentRequest
	15, // 34: tournament.TournamentService.CancelTournament:input_type -> tournament.CancelTournamentRequest
	17, // 35: tournament.TournamentService.RegisterForTournament:input_type -> tournament.RegisterForTournamentRequest
	19, // 36: tournament.TournamentService.GetTournamentParticipants:input_type -> tournament.GetTournamentParticipantsRequest
	21, // 37: tournament.TournamentService.RemoveParticipant:input_type -> tournament.RemoveParticipantRequest
	24, // 38: tournament.TournamentService.GetTournamentMatches:input_type -> tournament.GetTournamentMatchesRequest
	26, // 39: tournament.TournamentService.GetMatch:input_type -> tournament.GetMatchRequest
	28, // 40: tournament.TournamentService.SubmitMatchResult:input_type -> tournament.SubmitMatchResultRequest
	30, // 41: tournament.TournamentService.AdminSubmitMatchResult:input_type -> tournament.AdminSubmitMatchResultRequest
	6,  // 42: tournament.TournamentService.CreateTournament:output_type -> tournament.CreateTournamentResponse
	8,  // 43: tournament.TournamentService.ListTournaments:output_type -> tournament.ListTournamentsResponse
	10, // 44: tournament.TournamentService.GetTournament:output_type -> tournament.GetTournamentResponse
	12, // 45: tournament.TournamentService.ActivateTournament:output_type -> tournament.ActivateTournamentResponse
	14, // 46: tournament.TournamentService.StartTournament:output_type -> tournament.StartTournamentResponse
	16, // 47: tournament.TournamentService.CancelTournament:output_type -> tournament.CancelTournamentResponse
	18, // 48: tournament.TournamentService.RegisterForTournament:output_type -> tournament.RegisterForTournamentResponse
	20, // 49: tournament.TournamentService.GetTournamentParticipants:output_type -> tournament.GetTournamentParticipantsResponse
	22, // 50: tournament.TournamentService.RemoveParticipant:output_type -> tournament.RemoveParticipantResponse
	25, // 51: tournament.TournamentService.GetTournamentMatches:output_type -> tournament.GetTournamentMatchesResponse
	27, // 52: tournament.TournamentService.GetMatch:output_type -> tournament.GetMatchResponse
	29, // 53: tournament.TournamentService.SubmitMatchResult:output_type -> tournament.SubmitMatchResultResponse
	31, // 54: tournament.TournamentService.AdminSubmitMatchResult:output_type -> tournament.AdminSubmitMatchResultResponse
	42, // [42:55] is the sub-list for method output_type
	29, // [29:42] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
