// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: tournament.proto

package serviceextension

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TournamentStatus int32

const (
	TournamentStatus_TOURNAMENT_STATUS_UNSPECIFIED TournamentStatus = 0
	TournamentStatus_TOURNAMENT_STATUS_DRAFT       TournamentStatus = 1
	TournamentStatus_TOURNAMENT_STATUS_ACTIVE      TournamentStatus = 2
	TournamentStatus_TOURNAMENT_STATUS_STARTED     TournamentStatus = 3
	TournamentStatus_TOURNAMENT_STATUS_COMPLETED   TournamentStatus = 4
	TournamentStatus_TOURNAMENT_STATUS_CANCELLED   TournamentStatus = 5
)

// Enum value maps for TournamentStatus.
var (
	TournamentStatus_name = map[int32]string{
		0: "TOURNAMENT_STATUS_UNSPECIFIED",
		1: "TOURNAMENT_STATUS_DRAFT",
		2: "TOURNAMENT_STATUS_ACTIVE",
		3: "TOURNAMENT_STATUS_STARTED",
		4: "TOURNAMENT_STATUS_COMPLETED",
		5: "TOURNAMENT_STATUS_CANCELLED",
	}
	TournamentStatus_value = map[string]int32{
		"TOURNAMENT_STATUS_UNSPECIFIED": 0,
		"TOURNAMENT_STATUS_DRAFT":       1,
		"TOURNAMENT_STATUS_ACTIVE":      2,
		"TOURNAMENT_STATUS_STARTED":     3,
		"TOURNAMENT_STATUS_COMPLETED":   4,
		"TOURNAMENT_STATUS_CANCELLED":   5,
	}
)

func (x TournamentStatus) Enum() *TournamentStatus {
	p := new(TournamentStatus)
	*p = x
	return p
}

func (x TournamentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TournamentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tournament_proto_enumTypes[0].Descriptor()
}

func (TournamentStatus) Type() protoreflect.EnumType {
	return &file_tournament_proto_enumTypes[0]
}

func (x TournamentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TournamentStatus.Descriptor instead.
func (TournamentStatus) EnumDescriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{0}
}

type Tournament struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TournamentId        string                 `protobuf:"bytes,1,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxParticipants     int32                  `protobuf:"varint,4,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	CurrentParticipants int32                  `protobuf:"varint,5,opt,name=current_participants,json=currentParticipants,proto3" json:"current_participants,omitempty"`
	Status              TournamentStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=tournament.TournamentStatus" json:"status,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartTime           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Tournament) Reset() {
	*x = Tournament{}
	mi := &file_tournament_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tournament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tournament) ProtoMessage() {}

func (x *Tournament) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tournament.ProtoReflect.Descriptor instead.
func (*Tournament) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{0}
}

func (x *Tournament) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

func (x *Tournament) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tournament) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tournament) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *Tournament) GetCurrentParticipants() int32 {
	if x != nil {
		return x.CurrentParticipants
	}
	return 0
}

func (x *Tournament) GetStatus() TournamentStatus {
	if x != nil {
		return x.Status
	}
	return TournamentStatus_TOURNAMENT_STATUS_UNSPECIFIED
}

func (x *Tournament) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tournament) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Tournament) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Tournament) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateTournamentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,4,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTournamentRequest) Reset() {
	*x = CreateTournamentRequest{}
	mi := &file_tournament_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTournamentRequest) ProtoMessage() {}

func (x *CreateTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTournamentRequest.ProtoReflect.Descriptor instead.
func (*CreateTournamentRequest) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateTournamentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTournamentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTournamentRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *CreateTournamentRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateTournamentRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *Tournament            `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTournamentResponse) Reset() {
	*x = CreateTournamentResponse{}
	mi := &file_tournament_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTournamentResponse) ProtoMessage() {}

func (x *CreateTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTournamentResponse.ProtoReflect.Descriptor instead.
func (*CreateTournamentResponse) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTournamentResponse) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type ListTournamentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        TournamentStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=tournament.TournamentStatus" json:"status,omitempty"`
	StartDateFrom *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date_from,json=startDateFrom,proto3" json:"start_date_from,omitempty"`
	StartDateTo   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_date_to,json=startDateTo,proto3" json:"start_date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTournamentsRequest) Reset() {
	*x = ListTournamentsRequest{}
	mi := &file_tournament_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTournamentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTournamentsRequest) ProtoMessage() {}

func (x *ListTournamentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTournamentsRequest.ProtoReflect.Descriptor instead.
func (*ListTournamentsRequest) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{3}
}

func (x *ListTournamentsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListTournamentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTournamentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTournamentsRequest) GetStatus() TournamentStatus {
	if x != nil {
		return x.Status
	}
	return TournamentStatus_TOURNAMENT_STATUS_UNSPECIFIED
}

func (x *ListTournamentsRequest) GetStartDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDateFrom
	}
	return nil
}

func (x *ListTournamentsRequest) GetStartDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDateTo
	}
	return nil
}

type ListTournamentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournaments   []*Tournament          `protobuf:"bytes,1,rep,name=tournaments,proto3" json:"tournaments,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTournamentsResponse) Reset() {
	*x = ListTournamentsResponse{}
	mi := &file_tournament_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTournamentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTournamentsResponse) ProtoMessage() {}

func (x *ListTournamentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTournamentsResponse.ProtoReflect.Descriptor instead.
func (*ListTournamentsResponse) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{4}
}

func (x *ListTournamentsResponse) GetTournaments() []*Tournament {
	if x != nil {
		return x.Tournaments
	}
	return nil
}

func (x *ListTournamentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentRequest) Reset() {
	*x = GetTournamentRequest{}
	mi := &file_tournament_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentRequest) ProtoMessage() {}

func (x *GetTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentRequest.ProtoReflect.Descriptor instead.
func (*GetTournamentRequest) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{5}
}

func (x *GetTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type GetTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *Tournament            `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTournamentResponse) Reset() {
	*x = GetTournamentResponse{}
	mi := &file_tournament_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTournamentResponse) ProtoMessage() {}

func (x *GetTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTournamentResponse.ProtoReflect.Descriptor instead.
func (*GetTournamentResponse) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{6}
}

func (x *GetTournamentResponse) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type StartTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTournamentRequest) Reset() {
	*x = StartTournamentRequest{}
	mi := &file_tournament_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTournamentRequest) ProtoMessage() {}

func (x *StartTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTournamentRequest.ProtoReflect.Descriptor instead.
func (*StartTournamentRequest) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{7}
}

func (x *StartTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StartTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type StartTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *Tournament            `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTournamentResponse) Reset() {
	*x = StartTournamentResponse{}
	mi := &file_tournament_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTournamentResponse) ProtoMessage() {}

func (x *StartTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTournamentResponse.ProtoReflect.Descriptor instead.
func (*StartTournamentResponse) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{8}
}

func (x *StartTournamentResponse) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

type CancelTournamentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TournamentId  string                 `protobuf:"bytes,2,opt,name=tournament_id,json=tournamentId,proto3" json:"tournament_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTournamentRequest) Reset() {
	*x = CancelTournamentRequest{}
	mi := &file_tournament_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTournamentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTournamentRequest) ProtoMessage() {}

func (x *CancelTournamentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTournamentRequest.ProtoReflect.Descriptor instead.
func (*CancelTournamentRequest) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTournamentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CancelTournamentRequest) GetTournamentId() string {
	if x != nil {
		return x.TournamentId
	}
	return ""
}

type CancelTournamentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tournament    *Tournament            `protobuf:"bytes,1,opt,name=tournament,proto3" json:"tournament,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTournamentResponse) Reset() {
	*x = CancelTournamentResponse{}
	mi := &file_tournament_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTournamentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTournamentResponse) ProtoMessage() {}

func (x *CancelTournamentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tournament_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTournamentResponse.ProtoReflect.Descriptor instead.
func (*CancelTournamentResponse) Descriptor() ([]byte, []int) {
	return file_tournament_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTournamentResponse) GetTournament() *Tournament {
	if x != nil {
		return x.Tournament
	}
	return nil
}

var File_tournament_proto protoreflect.FileDescriptor

const file_tournament_proto_rawDesc = "" +
	"\n" +
	"\x10tournament.proto\x12\n" +
	"tournament\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x10permission.proto\"\xe3\x03\n" +
	"\n" +
	"Tournament\x12#\n" +
	"\rtournament_id\x18\x01 \x01(\tR\ftournamentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10max_participants\x18\x04 \x01(\x05R\x0fmaxParticipants\x121\n" +
	"\x14current_participants\x18\x05 \x01(\x05R\x13currentParticipants\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.tournament.TournamentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\x8a\x02\n" +
	"\x17CreateTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10max_participants\x18\x04 \x01(\x05R\x0fmaxParticipants\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"R\n" +
	"\x18CreateTournamentResponse\x126\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x16.tournament.TournamentR\n" +
	"tournament\"\x9e\x02\n" +
	"\x16ListTournamentsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.tournament.TournamentStatusR\x06status\x12B\n" +
	"\x0fstart_date_from\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rstartDateFrom\x12>\n" +
	"\rstart_date_to\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vstartDateTo\"t\n" +
	"\x17ListTournamentsResponse\x128\n" +
	"\vtournaments\x18\x01 \x03(\v2\x16.tournament.TournamentR\vtournaments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"Y\n" +
	"\x14GetTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"O\n" +
	"\x15GetTournamentResponse\x126\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x16.tournament.TournamentR\n" +
	"tournament\"[\n" +
	"\x16StartTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"Q\n" +
	"\x17StartTournamentResponse\x126\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x16.tournament.TournamentR\n" +
	"tournament\"\\\n" +
	"\x17CancelTournamentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rtournament_id\x18\x02 \x01(\tR\ftournamentId\"R\n" +
	"\x18CancelTournamentResponse\x126\n" +
	"\n" +
	"tournament\x18\x01 \x01(\v2\x16.tournament.TournamentR\n" +
	"tournament*\xd1\x01\n" +
	"\x10TournamentStatus\x12!\n" +
	"\x1dTOURNAMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TOURNAMENT_STATUS_DRAFT\x10\x01\x12\x1c\n" +
	"\x18TOURNAMENT_STATUS_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19TOURNAMENT_STATUS_STARTED\x10\x03\x12\x1f\n" +
	"\x1bTOURNAMENT_STATUS_COMPLETED\x10\x04\x12\x1f\n" +
	"\x1bTOURNAMENT_STATUS_CANCELLED\x10\x052\xdb\v\n" +
	"\x11TournamentService\x12\x9e\x02\n" +
	"\x10CreateTournament\x12#.tournament.CreateTournamentRequest\x1a$.tournament.CreateTournamentResponse\"\xbe\x01\x92AW\x12\x11Create Tournament\x1a4Create a new tournament with specified configurationb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18&ADMIN:NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x01\x82\xd3\xe4\x93\x020:\x01*\"+/v1/admin/namespace/{namespace}/tournaments\x12\x9f\x02\n" +
	"\x0fListTournaments\x12\".tournament.ListTournamentsRequest\x1a#.tournament.ListTournamentsResponse\"\xc2\x01\x92Ac\x12\x10List Tournaments\x1aAList tournaments with optional filtering by status and date rangeb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18 NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02.\x12,/v1/public/namespace/{namespace}/tournaments\x12\x8d\x02\n" +
	"\rGetTournament\x12 .tournament.GetTournamentRequest\x1a!.tournament.GetTournamentResponse\"\xb6\x01\x92AG\x12\x0eGet Tournament\x1a'Get tournament details by tournament IDb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18 NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x02\x82\xd3\xe4\x93\x02>\x12</v1/public/namespace/{namespace}/tournaments/{tournament_id}\x12\xb9\x02\n" +
	"\x0fStartTournament\x12\".tournament.StartTournamentRequest\x1a#.tournament.StartTournamentResponse\"\xdc\x01\x92A_\x12\x10Start Tournament\x1a=Start a tournament to generate brackets and begin competitionb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18&ADMIN:NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02F:\x01*\"A/v1/admin/namespace/{namespace}/tournaments/{tournament_id}/start\x12\xb6\x02\n" +
	"\x10CancelTournament\x12#.tournament.CancelTournamentRequest\x1a$.tournament.CancelTournamentResponse\"\xd6\x01\x92AX\x12\x11Cancel Tournament\x1a5Cancel a tournament and prevent further participationb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18&ADMIN:NAMESPACE:{namespace}:TOURNAMENT\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02G:\x01*\"B/v1/admin/namespace/{namespace}/tournaments/{tournament_id}/cancelB\xbc\x01\x92AE\x12\x15\n" +
	"\x0eTournament API2\x031.0\"\v/tournamentZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02\n" +
	"%net.accelbyte.extend.serviceextensionP\x01Z%accelbyte.net/extend/serviceextension\xaa\x02!AccelByte.Extend.ServiceExtensionb\x06proto3"

var (
	file_tournament_proto_rawDescOnce sync.Once
	file_tournament_proto_rawDescData []byte
)

func file_tournament_proto_rawDescGZIP() []byte {
	file_tournament_proto_rawDescOnce.Do(func() {
		file_tournament_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tournament_proto_rawDesc), len(file_tournament_proto_rawDesc)))
	})
	return file_tournament_proto_rawDescData
}

var file_tournament_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tournament_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tournament_proto_goTypes = []any{
	(TournamentStatus)(0),            // 0: tournament.TournamentStatus
	(*Tournament)(nil),               // 1: tournament.Tournament
	(*CreateTournamentRequest)(nil),  // 2: tournament.CreateTournamentRequest
	(*CreateTournamentResponse)(nil), // 3: tournament.CreateTournamentResponse
	(*ListTournamentsRequest)(nil),   // 4: tournament.ListTournamentsRequest
	(*ListTournamentsResponse)(nil),  // 5: tournament.ListTournamentsResponse
	(*GetTournamentRequest)(nil),     // 6: tournament.GetTournamentRequest
	(*GetTournamentResponse)(nil),    // 7: tournament.GetTournamentResponse
	(*StartTournamentRequest)(nil),   // 8: tournament.StartTournamentRequest
	(*StartTournamentResponse)(nil),  // 9: tournament.StartTournamentResponse
	(*CancelTournamentRequest)(nil),  // 10: tournament.CancelTournamentRequest
	(*CancelTournamentResponse)(nil), // 11: tournament.CancelTournamentResponse
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_tournament_proto_depIdxs = []int32{
	0,  // 0: tournament.Tournament.status:type_name -> tournament.TournamentStatus
	12, // 1: tournament.Tournament.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: tournament.Tournament.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: tournament.Tournament.start_time:type_name -> google.protobuf.Timestamp
	12, // 4: tournament.Tournament.end_time:type_name -> google.protobuf.Timestamp
	12, // 5: tournament.CreateTournamentRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 6: tournament.CreateTournamentRequest.end_time:type_name -> google.protobuf.Timestamp
	1,  // 7: tournament.CreateTournamentResponse.tournament:type_name -> tournament.Tournament
	0,  // 8: tournament.ListTournamentsRequest.status:type_name -> tournament.TournamentStatus
	12, // 9: tournament.ListTournamentsRequest.start_date_from:type_name -> google.protobuf.Timestamp
	12, // 10: tournament.ListTournamentsRequest.start_date_to:type_name -> google.protobuf.Timestamp
	1,  // 11: tournament.ListTournamentsResponse.tournaments:type_name -> tournament.Tournament
	1,  // 12: tournament.GetTournamentResponse.tournament:type_name -> tournament.Tournament
	1,  // 13: tournament.StartTournamentResponse.tournament:type_name -> tournament.Tournament
	1,  // 14: tournament.CancelTournamentResponse.tournament:type_name -> tournament.Tournament
	2,  // 15: tournament.TournamentService.CreateTournament:input_type -> tournament.CreateTournamentRequest
	4,  // 16: tournament.TournamentService.ListTournaments:input_type -> tournament.ListTournamentsRequest
	6,  // 17: tournament.TournamentService.GetTournament:input_type -> tournament.GetTournamentRequest
	8,  // 18: tournament.TournamentService.StartTournament:input_type -> tournament.StartTournamentRequest
	10, // 19: tournament.TournamentService.CancelTournament:input_type -> tournament.CancelTournamentRequest
	3,  // 20: tournament.TournamentService.CreateTournament:output_type -> tournament.CreateTournamentResponse
	5,  // 21: tournament.TournamentService.ListTournaments:output_type -> tournament.ListTournamentsResponse
	7,  // 22: tournament.TournamentService.GetTournament:output_type -> tournament.GetTournamentResponse
	9,  // 23: tournament.TournamentService.StartTournament:output_type -> tournament.StartTournamentResponse
	11, // 24: tournament.TournamentService.CancelTournament:output_type -> tournament.CancelTournamentResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_tournament_proto_init() }
func file_tournament_proto_init() {
	if File_tournament_proto != nil {
		return
	}
	file_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tournament_proto_rawDesc), len(file_tournament_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tournament_proto_goTypes,
		DependencyIndexes: file_tournament_proto_depIdxs,
		EnumInfos:         file_tournament_proto_enumTypes,
		MessageInfos:      file_tournament_proto_msgTypes,
	}.Build()
	File_tournament_proto = out.File
	file_tournament_proto_goTypes = nil
	file_tournament_proto_depIdxs = nil
}
